using System.Net.Mime;
using Backend_AuraNeuro.API.NeurologicalHealth.Domain.Model.Aggregates;
using Backend_AuraNeuro.API.NeurologicalHealth.Domain.Model.Queries;
using Backend_AuraNeuro.API.NeurologicalHealth.Domain.Services.Command;
using Backend_AuraNeuro.API.NeurologicalHealth.Domain.Services.Queries;
using Backend_AuraNeuro.API.NeurologicalHealth.Interface.REST.Resources;
using Backend_AuraNeuro.API.NeurologicalHealth.Interface.REST.Transform;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace Backend_AuraNeuro.API.NeurologicalHealth.Interface.REST;

[ApiController]
[Route("/api/v1/[controller]")]
[Produces(MediaTypeNames.Application.Json)]
public class NeuroAssessmentController(
    INeuroAssessmentCommandService neuroAssessmentCommandService,
    INeuroAssessmentQueryService neuroAssessmentQueryService
    ): ControllerBase
{
    
    [HttpPost]
    [SwaggerOperation(
        Summary = "Create a neuro assessment",
        Description = "create a neurological evaluation generated by the neurologist")]
    [SwaggerResponse(200, "NeuroAssessment created", typeof(NeuroAssessment))]
    [SwaggerResponse(400, "Invalid Request")]
    public async Task<IActionResult> CreateNeuroAssessment([FromBody] CreateNeuroAssessmentCommandResource neuroAssessmentCommandResource)
    {
        try
        {
            var result =
                await neuroAssessmentCommandService.Handle(
                    CreateNeuroAssessmentFromResource.ToCommandFromResource(neuroAssessmentCommandResource));
            if (result is null) return BadRequest();
            return Ok(result);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return BadRequest();
        }
    }

    [HttpGet("patient/{patientId:long}")]
    public async Task<IActionResult> FindNeuroAssessmentPatient(long patientId)
    {
        try
        {
            var result = await neuroAssessmentQueryService.Handle(new GetNeuroAssessmentsByPatientIdQuery(patientId));
            return Ok(result);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return BadRequest();
        }
    }

    [HttpGet("neurologist/{neurologistId:long}")]
    public async Task<IActionResult> FindNeuroAssessmentNeurologist(long neurologistId)
    {
        try
        {
            var result =
                await neuroAssessmentQueryService.Handle(new GetNeuroAssessmentsByNeurologistIdQuery(neurologistId));
            return Ok(result);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return BadRequest();
        }
    }
} 